server:
  port: 8090

api: 
  coingecko:
    domain: "https://api.coingecko.com/api/v3"
    endpoints:
      coins : "/coins/markets"
    key: "&x_cg_demo_api_key=CG-WMdqgRJLLNwTQStejmEWZjSz"

redis:
  key:
    coins: "crypto:coingecko:coins-markets:"